<a href="https://colab.research.google.com/github/Shaik66-pro/Python_Course_work/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4,5])
print("1-dim",arr1,sep='\n',end = "\n\n")

arr2 = np.array([[1, 2, 3], [4,5,6]])
print("2-dim",arr2,sep='\n',end = "\n\n")

arr3 = np.array([[[1, 2], [3,4]], [[5,6], [7,8]]])
print("multi-dim",arr3,sep='\n')



1-dim
[1 2 3 4 5]

2-dim
[[1 2 3]
 [4 5 6]]

multi-dim
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
zeros = np.zeros((10,4))
print(zeros)

In [9]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
identity = np.eye((7))
print(identity)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
